### ISSUE TITLE
Separator Type Inconsistency in Chain Concatenation

### ISSUE THREAD

**Issue by nevillco** [Raizlabs/BonMot#160]
Concatenating `BONChain` with `BONText.joinTextables` takes a `BONChain` as a separator, while using `BONChain().appendLink` takes a String as a separator. Should deprecate current version of `appendLink` with `separator` parameter and introduce one with a `separatorTextable` of type `id<BONTextable>`.

**Comment by ZevEisenberg** [comment]
The documentation also says that `joinTextables` and `appendLink:separator:` result in different behaviors for the separator, but they appear not to. Making this change will sidestep the problem by making the separator a fully specified `BONTextable`.

Also: the parameter should probably be `separatorTextable:`, since it should take a value of type `id<BONTextable>`.
