### ISSUE TITLE
HTML support

### ISSUE THREAD

**Issue by prsolucoes** [Raizlabs/BonMot#172]
Hi,

Nice library. It has HTML support?

Thanks.

**Comment by ZevEisenberg** [comment]
Hi, @prsolucoes. Thanks for your question. BonMot does not currently have full HTML support - for that, you'd have to [use use the `NSHTMLTextDocumentType` option](NSHTMLTextDocumentType) when constructing an `NSAttributedString`. However, BonMot has support for [tagging ranges of text](https://github.com/Raizlabs/BonMot#tag-styles) in an HTML-like way. However, it may not be complete enough to suit your needs.

@KingOfBrian and I are working on a major update to BonMot, and it may include better (though still incomplete) HTML support by using an XML parser. Would you mind telling us a little bit about your use case? We'd like to know what types of things people are using BonMot for, in order to better support common uses.

**Comment by prsolucoes** [comment]
Hi,

Im not using today. But i have an app called Ubook (ubook.com) and on product details screen we have a description label that need support some HTML tags, like "br", "b", "strong", "i" and more. Will be nice if we can use it.

We have another places that we want BOLD a string. But today we are using our own implementation to BOLD. 

Thanks.

**Comment by ZevEisenberg** [comment]
@prsolucoes you can use BonMot for any HTML-style tags, and you can even define custom begin and end strings for each tag (for example, you could match `<b id="1">some text</b>`), but it's only exact matching, so you couldn't match any arbitrary `id` value, for example. Another caveat is that nested tags are not currently supported. However, nesting support is planned for BonMot 4.0 (the Swift rewrite).

**Comment by KingOfBrian** [comment]
The upcoming 4.0 release will have better HTML support. If you're interested in checking it out, look at PR #180.
