### ISSUE TITLE
Get the actual height after apply the attributed text.

### ISSUE THREAD

**Issue by ram2386** [Raizlabs/BonMot#182]
Thanks for sharing the library which is very useful to provide attribute text.

It would be possible to get the height of whole text after apply the attributed text. 
As I had implemented an application where I have to show the description with mix of images and font styles in the list. And I have used the UITableView for listing those description, so if I can get the actual height after apply the attributed text then I can simply get the value and apply on the UITableView heightForRowAtIndexPath delegate.

**Comment by ZevEisenberg** [comment]
Hi, @ram2386, and thanks for your question! There are two common ways to achieve what you're looking for:

1. Use [self-sizing table view cells](https://www.raywenderlich.com/129059/self-sizing-table-view-cells). This uses Auto Layout to measure your cells after they're configured, so you don't have to calculate the height yourself. It was introduced in iOS 8, it works quite well in iOS 9, and in iOS 10 they made some nice improvements which you can learn about in the [WWDC session from this year on `UICollectionView`](https://developer.apple.com/videos/play/wwdc2016/219/), which covers topics that also apply to `UITableView`. This is the method I recommend.
2. You can also measure an attributed string yourself using `-[NSAttributedString boundingRectWithSize:options:]`. You can read more about it on [this StackOverflow thread](http://stackoverflow.com/a/2460091/255489).

I would definitely go with option 1 if you can, because it's a lot less code to write.

Will one of these options work for you? Please let me know if you can think of a way that BonMot can make this task easier. Good luck!
