### ISSUE TITLE
About detect attribute string when user tap in UIlabel(or textview ....)

### ISSUE THREAD

**Issue by DanielLe232** [Raizlabs/BonMot#276]
Hi raiz,
I found all function in your framework, I don't see any function implement detect attribute string when user tap in it (maybe i miss it)
I think this framework must have this feature. :)
example:
I want add "new feature"
===> when user tap in "new feature" it will call action.

Could you please support me? :)

**Comment by ZevEisenberg** [comment]
Hi, @DanielLe232,

Thanks for writing in. Tapping links isn't a feature of BonMot, because BonMot just provides utilities for constructing attributed strings. However, it _does_ let you embed `URL`s in attributed strings with the `link` property on `StringStyle` and corresponding `StringStyle.Part.link`. You can then use `UITextView`, which supports detecting and tapping links, or use a technique like [this](http://samwize.com/2016/03/04/how-to-create-multiple-tappable-links-in-a-uilabel/) to do it yourself, or use a library like [TTTAttributedLabel](https://github.com/TTTAttributedLabel/TTTAttributedLabel), which supports tappable links in labels.

Note that, unless you're using a `UITextView`, you'll probably have to style your links like this:

```swift
StringStyle(
    .link(someURL as NSURL),
    .color(UIColor.blue),
    .underline(.styleSingle, nil)
)
```

Also, the need for `as NSURL` is something that I just noticed, and I'm going to fix it soon in an upcoming release.

Please let me know if you have any other questions!
