### ISSUE TITLE
Processing <a> tags

### ISSUE THREAD

**Issue by r-a-o** [Raizlabs/BonMot#285]
I have the following markup that I want to style using BonMot, 

`<p>This is a <i>simple</i> <b>paragraph text</b> with an embedded <a href="http://google.com/">link</a>. </p>`

I am able to apply different colors and fonts, but unable to make `<a>` tag clickable. 

```swift
let bStyle = StringStyle(
    .font(Config.Font.get(.para_BOLD, size: fontSize))
)

let iStyle = StringStyle(
    .font(Config.Font.get(.para_ITALIC, size: fontSize))
)

let aStyle = StringStyle(
    .font(Config.Font.get(.para_ITALIC, size: fontSize)),
    .color(.blue),
    .link(URL(string: "http://example.com/")!)
)

let contentStyle = StringStyle(
    .font(Config.Font.get(fontName, size: fontSize)),
    .lineHeightMultiple(1.2),
    .color(.black),
    .xmlRules([
        .style("b", bStyle),
        .style("i", iStyle),
        .style("a", aStyle),
    ])
)

let attributedString = html.styled(with: contentStyle)
let contentTextPart = Label()
contentTextPart.numberOfLines = 0
contentTextPart.attributedText = attributedString 
```

Not sure why the link isn't working. Can anybody please help me with this?

**Comment by r-a-o** [comment]
Also, how do I make `.link()` extract `href` property of the `<a>` tag instead of having to pass a URL param to it?

**Comment by ZevEisenberg** [comment]
@r-a-o thanks for writing in! Since BonMot is just for creating attributed strings, it won't help you with tapping links (currently - we may add it in the future). In the meantime, you might want to check out [TTTAttributedLabel](https://github.com/TTTAttributedLabel/TTTAttributedLabel), which is a `UILabel` replacement that supports link tapping.

As for parsing the `<a>` tags to extract `.link()`, it's not something that is supported out of the box, but you should be able to do what you need by passing in a custom XML styler. Look at the `XMLStyler` protocol in `XMLBuilder.swift`. You can make your own type conform to that protocol, and return the appropriate values when you come to an `<a>` tag. See the implementation of the `Styler` nested inside `XMLStyleRule` a little earlier in the same file - it should provide a good starting point.

Then, you'll pass your custom styler into your string style like this:

```swift
let contentStyle = StringStyle(
    .font(Config.Font.get(fontName, size: fontSize)),
    .lineHeightMultiple(1.2),
    .color(.black),
    .xmlRules([
        ... // existing rules
    ])
    .xmlStyler(MyXMLStyler())
)
```

I know this is more involved than one might like, so please don't hesitate to post here if something is unclear or if you have more questions. I'm interested in making tasks like these easier in the future - maybe we could build a default HTML link styler.

**Comment by r-a-o** [comment]
Yes, I want to write up a XMLStyler which extracts `href` from `<a href="">link_text</a>` tag. Once that is done, I want to see if I can register a tap gesture that allows me to detect a tap on "link_text" range, something like this, http://samwize.com/2016/03/04/how-to-create-multiple-tappable-links-in-a-uilabel/#on-tap-event .  Thoughts?
TTTAttributedLabel is in objective C, I think there is no swift alternative.

**Comment by ZevEisenberg** [comment]
That sounds like the right approach. I wouldn't avoid TTTAttributedLabel just because it's Objective-C. All of Foundation and UIKit are still running on Objective-C. A little Objective-C never hurt anyone 😉

**Comment by r-a-o** [comment]
Yes of course :) 
Now I have added TTTAttributedLabel, but now I am unable to figure out how to parse for all the <a> tags in my <p> tag so that I can make them links. 

html: `<p>This is a <i>simple</i> <a href="http://example.com/somelink">paragraph text</a> with an embedded <a href="http://google.com/">link</a>. </p>`

```
let contentTextPart = TTTAttributedLabel(frame: CGRect.zero)
contentTextPart.delegate = self
// Applying BonMot styles for b/i/a tags,
contentTextPart.attributedText = html.styled(with: contentStyle)
```
Now I am able to set attributedText of TTTAttributedLabel label using BonMot styles on my `html`.

Now I need to parse and loop through all of my `<a>` tags and collect `link_text` and `href` so I can run the below code in a loop on all the anchor tags. 

```
let range:NSRange = (contentTextPart.text as! NSString).range(of: "link_text")
contentTextPart.addLink(to: URL(string: "http://example.com/link/"), with: range)
```
_Couldn't figure out how to parse my html and extract <a> tag text and href._

**Comment by Imperiopolis** [comment]
@r-a-o In your XMLStyler, overwrite `styleForElement` like so

```swift
struct MyCustomStyler: XMLStyler {
    func style(forElement name: String, attributes: [String: String], currentStyle: StringStyle) -> StringStyle? {
        switch name {
        case "a":
            guard let href = attributes["href"], let url = URL(string: href) else { return nil }
            return StringStyle(.link(url))
        default:
            return nil
        }
    }

    func prefix(forElement name: String, attributes: [String: String]) -> Composable? { return nil }
    func suffix(forElement name: String) -> Composable? { return nil }
}

let string = "This is a simple embedded <a href='http://google.com/'>link</a>.".styled(with: StringStyle(.xmlStyler(MyCustomStyler()))

```

If you're using a `UITextView` and your link is a fully qualified link (starts with a valid scheme) it will now be tappable and open in safari. You can also assign this to something like `TTTAttributedLabel` and I believe it will also just work

**Comment by ZevEisenberg** [comment]
I'm going to close this since it sounds like things are working, but feel free to reopen if you have more questions 😃
