### ISSUE TITLE
.lineSpacing ignores default alignment

### ISSUE THREAD

**Issue by armandsLa** [Raizlabs/BonMot#300]
I'm not sure if this is intended or not, but when `.lineSpacing` is added, `textAlignemt` set in IB is ignored. It does not happen when I add `.tracking`.

**Comment by ZevEisenberg** [comment]
That makes sense, because line spacing and text alignment are both specified using an `NSParagraphStyle`, and when you set the line spacing with BonMot, it clobbers the paragraph style that was set up in IB. My advice is to specify all your styling in one place: in code. Otherwise, you'll need to write code that can find the alignment already applied to the view, mix it into the `StringStyle`, and re-apply it to the view.
