### ISSUE TITLE
Support for mixing bold/italic fonts with tags

### ISSUE THREAD

**Issue by joeboyscout04** [Raizlabs/BonMot#303]
Are there any plans to support nested tags? This would be very useful to apply bold+italic for example:

"I'd like to call <b><i>your</i> attention to this</b>."

Thanks,

**Comment by ZevEisenberg** [comment]
@joeboyscout04 thanks for your question! BonMot already supports nested tags as a general rule. For example, you can have a style with red text, and use XML to apply underlining to just part of the text.

However, as you observe, we don't currently support using nested tags to mix normal, bold, and italic styles of text. The trick would be to determine if, given an arbitrary `UIFont`, we can generate the applicable bold, italic, bold+italic, or normal variant of that font. And what about support for other weights like _semibold_ and _thin_? It's definitely a good idea, but we need to look into whether we can do this kind of font transformation in general.

Definitely interested in ideas from you or anyone else in the community as to how this would work! Maybe there's something we can do with `UIFontDescriptor`?

**Comment by joeboyscout04** [comment]
I understand.  I think UIFontDescriptor has an addingAttributes ability that could work in this case where we want to add additional descriptors to an existing font within a nested set of tags.

**Comment by ZevEisenberg** [comment]
Here's a code snippet to make a font italic:

```swift
extension UIFont {

    func italicized() -> UIFont? {
        var traits = fontDescriptor.symbolicTraits
        traits.insert([.traitItalic])
        if let newDesciptor = fontDescriptor.withSymbolicTraits(traits) {
            return UIFont(descriptor: newDesciptor, size: pointSize)
        }
        return nil
    }

}
```

`UIFont` and `NSFont` expose the following traits:

- italic
- bold
- expanded
- condensed
- monospace
- vertical
- UI Optimized
- tight leading
- loose leading

In addition, the following traits are exposed:

- oldstyle serifs
- transitional serifs
- modern serifs
- Clarendon serifs
- slab serifs
- freeform serifs
- san serif
- ornamentals
- scripts
- symbolic

Although these two sets of values are both part of `UIFontDescriptorSymbolicTraits`, they are clearly of two kinds: the first set are variants that can be switched on for fonts that support them, e.g. a bold or italic version of a font; the second set are attributes of a font that can be used to describe it, but can't be switched on and off. BonMot should expose these as separate types.

What should the API for this look like? Here's an option:

```swift
StringStyle(.attributes(.bold)) // single attribute
StringStyle(.attributes([.bold, .italic])) // multiple attributes
```

Is the word `attributes` discoverable enough? Anyone have any alternative suggestions?

We should also have a mechanism to determine whether a given font has a given feature, analogous to `BonMot.has(feature:)`. It would be something like `UIFont.has(attribute:)`. But what about the second set of attributes, the serif/etc ones? Should that be exposed as a separate method? What should that one look like?

Alternative suggestion: don't differentiate between the two different attributes. This is the simplest, but I don't like it, because one of the goals of BonMot is to abstract over design warts of the text system, and the conflation of these two attribute types is one of those warts. It shouldn't be possible to use BonMot to ask for "the serif version of this font," unless that's a question you can actually ask of a font. Anyone have any examples of cases where it is?
