### ISSUE TITLE
Nullability and Generics

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/BonMot#31]
All the cool kids are using it.

**Comment by ateliercw** [comment]
If you add good nullability annotations, it shouldn't be bad to use as a framework with swift.

I'd rather see carthage support for making it more Swift friendly.

**Comment by ZevEisenberg** [comment]
Carthage support will be added in #32

**Comment by jvisenti** [comment]
@ZevEisenberg Second the request for nullability annotations. Specifically it's a problem because BonMot lets you pass in an optional string to BONChain (it's force unwrapped), but this will crash. This should be required `nonnull` because `NSAttributedString` crashes with a nil string.

But really more generally everything being force unwrapped (the default w/ no annotations) is very dangerous.
