### ISSUE TITLE
Alignment for substrings within a single UILabel

### ISSUE THREAD

**Issue by mattThousand** [Raizlabs/BonMot#59]
<img width="432" alt="screen shot 2015-08-14 at 10 46 34 am" src="https://cloud.githubusercontent.com/assets/2637355/9276435/f0a81160-4271-11e5-92a4-49c65ed64e82.png">

Wondering if it might be possible to left/center/right align substrings within a UILabel

**Comment by ZevEisenberg** [comment]
This requires the use of left and right tab stops in paragraph styles. Definitely worth exploring! A possible issue is that I believe tab stops are typically specified in points from the start of the line, so what happens when the label changes size? Might need to use a UILabel subclass that updates its string when its size changes?

**Comment by ZevEisenberg** [comment]
After looking at this with @mattThousand, we determined that this is probably accomplished with two labels and auto layout or a stack view on iOS 9. Even if it is done with tab stops, it should probably be its own thing, since it wouldn’t necessarily make use of anything in this library.
